Repository FGA0138-MDS-Ajax/2023-2-SIRIUS, pull requests merged in 2023-11, with the labels that each got.

#25 Documentacao sprint
  docs/sprints/criar_arquivos_sprint.py
  docs/sprints/sprint-1/s1-dailies.md
  docs/sprints/sprint-1/s1-planning.md
  docs/sprints/sprint-1/s1-review-retrospective.md
Labels: documentation

#27 Documento de arquitetura
  arquitetura-sirius.pdf
  docs/detalhamento.jpeg
  docs/diagrama-classes.jpeg
  docs/diagrama-implementacao.jpeg
  docs/diagrama-pacotes.jpeg
  docs/documento-arquitetura.md
  mkdocs.yml
Labels: documentation, organização, entrega, sprint 1

#28 Homol
  arquitetura-sirius.pdf
  docs/detalhamento.jpeg
  docs/diagrama-classes.jpeg
  docs/diagrama-implementacao.jpeg
  docs/diagrama-pacotes.jpeg
  docs/documento-arquitetura.md
  mkdocs.yml
Labels: documentation, sprint 1

#24 Adicionando PR Template e Bug Report Template.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/task-genérica.md
  .github/ISSUE_TEMPLATE/user-story.md
  .github/pull_request_template.md
  backend/.docker/Dockerfile
  backend/.dockerignore
  backend/README.md
  backend/docker-compose.yml
  backend/dockerfile
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/controllers/CSV/CSVController.ts
  backend/src/index.ts
  backend/src/routes.ts
  backend/yarn.lock
  docs/escopo.md
  docs/visao-produto-projeto.md
  frontend/.eslintrc.cjs
  frontend/.gitignore
  frontend/README.md
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/src/App.tsx
  frontend/src/components/ButtonExample/index.tsx
  frontend/src/components/NavbarExample/index.tsx
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/pages/Home/index.tsx
  frontend/src/pages/Login/index.tsx
  frontend/src/server/api.ts
  frontend/src/tests/index.test.ts
  frontend/src/types/index.ts
  frontend/src/utils/example.ts
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: organização

#46 Adição da documentação da sprint 3
  docs/sprints/sprint-3/s3-dailies.md
  docs/sprints/sprint-3/s3-planning.md
  docs/sprints/sprint-3/s3-review-retrospective.md
Labels: documentation, organização

#50 Doc sprint4
  docs/sprints/sprint-4/s4-dailies.md
  docs/sprints/sprint-4/s4-planning.md
  docs/sprints/sprint-4/s4-review-retrospective.md
Labels: documentation, organização
